geocoder_projeto/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :places, except: [:update, :edit, :destroy]
  root 'places#index'
end

geocoder_projeto/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

geocoder_projeto/app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :address, latitude: :latitude, longitude: :longitude
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

geocoder_projeto/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

geocoder_projeto/app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.order('created_at DESC')
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Place added!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  private

  def place_params
    params.require(:place).permit(:title, :address, :visited_by)
  end
end

geocoder_projeto/app/helpers/application_helper.rb
module ApplicationHelper
end

geocoder_projeto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeocoderProjeto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

geocoder_projeto/app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <fieldset class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :visited_by %>
    <%= f.text_field :visited_by, class: "form-control" %>
  </fieldset>

  <fieldset class="form-group">
    <%= f.label :address, 'Address' %>
    <%= f.text_field :address, class: "form-control" %>
  </fieldset>

  <%= f.submit 'Add!', class: 'btn btn-primary' %>
<% end %>

geocoder_projeto/app/views/places/_place.html.erb
<li>
  <%= link_to place.title, place_path(place) %>
  visited by <strong><%= place.visited_by %></strong>
</li>

geocoder_projeto/app/views/places/index.html.erb
<header><h1 class="display-4">Places</h1></header>

<%= link_to 'Add place', new_place_path, class: 'btn btn-primary btn-lg' %>

<div class="card">
  <div class="card-block">
    <ul>
      <%= render @places %>
    </ul>
  </div>
</div>

geocoder_projeto/app/views/places/new.html.erb
<header><h1 class="display-4">Add Place</h1></header>

<%= render 'form' %>

geocoder_projeto/app/views/places/show.html.erb
<header><h1 class="display-4"><%= @place.title %></h1></header>

<p>Address: <%= @place.address %></p>
<p>Coordinatesh: <%= @place.latitude %> <%= @place.longitude %></p>